const axios = require('axios');

async function testAPIs() {
  const BASE_URL = 'http://localhost:5000/api';
  console.log('--- STARTING API TESTS ---');
  
  try {
    // 1. Login
    console.log('1. Logging in as david@test.com...');
    const loginRes = await axios.post(`${BASE_URL}/auth/login`, {
      email: 'david@test.com',
      password: '12345678'
    });
    const token = loginRes.data.token;
    console.log('Login successful! Token acquired.');
    
    const config = { headers: { Authorization: `Bearer ${token}` } };
    
    // 2. Metadata API Tests
    console.log('\n2. Testing Metadata APIs...');
    console.log('Creating simple metadata entry...');
    const metaCreateRes = await axios.post(`${BASE_URL}/admin/metadata`, {
      type: 'branch',
      value: 'TEST_BRANCH_1',
      priority: 99
    }, config);
    const newMetaId = metaCreateRes.data.metadata._id;
    console.log(`Created Metadata ID: ${newMetaId}`);
    
    console.log('Fetching all metadata...');
    const metaGetRes = await axios.get(`${BASE_URL}/metadata`);
    const branches = metaGetRes.data.branch || [];
    const found = branches.find(b => b.value === 'TEST_BRANCH_1');
    console.log(`Fetch successful! Created branch found: ${!!found}`);
    
    console.log(`Deactivating Metadata...`);
    await axios.patch(`${BASE_URL}/admin/metadata/${newMetaId}`, { isActive: false }, config);
    console.log('Deactivated successfully.');
    
    // Deactivate it, but we need it active to create a notification for it!
    console.log(`Re-activating Metadata for notification test...`);
    await axios.patch(`${BASE_URL}/admin/metadata/${newMetaId}`, { isActive: true }, config);
    
    // 3. Notification API Tests
    console.log('\n3. Testing Notification APIs...');
    console.log('Creating notification...');
    const notifCreateRes = await axios.post(`${BASE_URL}/admin/notifications`, {
      title: 'Test Notification',
      content: 'This is a test notification generated by script',
      category: 'notice',
      targetBranch: 'TEST_BRANCH_1'
    }, config);
    const newNotifId = notifCreateRes.data.notification._id;
    console.log(`Created Notification ID: ${newNotifId}`);
    
    console.log('Fetching notifications...');
    const notifGetRes = await axios.get(`${BASE_URL}/notifications`, config);
    const notifs = notifGetRes.data || [];
    const foundNotif = notifs.find(n => n.title === 'Test Notification');
    console.log(`Fetch successful! Created notification found: ${!!foundNotif}`);
    
    console.log(`Voting to delete Notification...`);
    await axios.patch(`${BASE_URL}/admin/notifications/${newNotifId}/vote-delete`, {}, config);
    console.log('Voted successfully.');
    
    console.log(`Force deleting Notification...`);
    await axios.delete(`${BASE_URL}/admin/notifications/${newNotifId}`, config);
    console.log('Notification deleted successfully.');
    
    console.log(`Deleting Metadata...`);
    await axios.delete(`${BASE_URL}/admin/metadata/${newMetaId}`, config);
    console.log('Metadata deleted successfully.');
    
    console.log('\n--- ALL TESTS PASSED SUCCESSFULLY ---');
  } catch (err) {
    console.error('\n!!! TEST FAILED !!!');
    if (err.response) {
      console.error(`Status: ${err.response.status}`);
      console.error(`Data:`, err.response.data);
      console.error(`Route: ${err.response.config.method.toUpperCase()} ${err.response.config.url}`);
    } else {
      console.error(err.message);
    }
  }
}

testAPIs();
